const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const PORT=process.env.PORT||3000,DB=path.join(__dirname,"data.json"),PUBLIC=path.join(__dirname,"public");
const initial={"users":[{"id":"U1","name":"Siswa Demo","email":"siswa@sekolah.id","password":"siswa123","role":"siswa"},{"id":"U2","name":"Pengurus Perpustakaan","email":"pengurus@perpus.id","password":"admin123","role":"pengurus"}],"books":[{"id":"BK-001","title":"Matematika untuk SMK Kelas X","author":"Tim Edukasi","category":"Pelajaran","stock":3},{"id":"BK-002","title":"Bahasa Indonesia Kelas VIII","author":"Pusat Kurikulum","category":"Pelajaran","stock":2},{"id":"BK-003","title":"IPA Terpadu","author":"Tim Sains","category":"Sains","stock":2},{"id":"BK-004","title":"Ilmu Pengetahuan Sosial","author":"Tim IPS","category":"Sosial","stock":2},{"id":"BK-005","title":"English Daily Conversation","author":"English Team","category":"Bahasa","stock":2},{"id":"BK-006","title":"Kumpulan Cerita Nusantara","author":"R. Pratama","category":"Sastra","stock":2},{"id":"BK-007","title":"Pemrograman Dasar","author":"Digital Lab","category":"Teknologi","stock":2},{"id":"BK-008","title":"Pendidikan Agama Islam","author":"Tim PAI","category":"Agama","stock":2}],"loans":[]};
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(initial,null,2));
let db=JSON.parse(fs.readFileSync(DB,"utf8")),sessions=new Map();
const mime={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".json":"application/json"};
const send=(res,s,d,t="application/json")=>{res.writeHead(s,{"Content-Type":t,"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS"});res.end(t==="application/json"?JSON.stringify(d):d)};
const body=req=>new Promise((ok,no)=>{let x="";req.on("data",c=>x+=c);req.on("end",()=>{try{ok(x?JSON.parse(x):{})}catch(e){no(e)}})});
const auth=req=>sessions.get((req.headers.authorization||"").replace("Bearer ",""));
const newid=p=>p+"-"+crypto.randomBytes(5).toString("hex").toUpperCase();
const save=()=>fs.writeFileSync(DB,JSON.stringify(db,null,2));
http.createServer(async(req,res)=>{
try{
if(req.method==="OPTIONS")return send(res,204,{});
if(req.url==="/api/login"&&req.method==="POST"){let b=await body(req),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),name=String(b.name||"").trim();if(!/^\S+@\S+\.\S+$/.test(email))return send(res,400,{error:"Masukkan alamat email yang valid."});let u=db.users.find(x=>x.email.toLowerCase()===email&&x.role===b.role);if(!u && b.role==="siswa"){if(!name)return send(res,400,{error:"Nama wajib diisi untuk akun siswa baru."});if(password.length<6)return send(res,400,{error:"Password minimal 6 karakter."});u={id:newid("U"),name,email,password,role:"siswa"};db.users.push(u);save()}else if(!u || u.password!==password){return send(res,401,{error:"Email, password, atau peran salah."})}let token=crypto.randomBytes(24).toString("hex");sessions.set(token,u);return send(res,200,{token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
let u=auth(req);
if(req.url==="/api/me"){if(!u)return send(res,401,{error:"Belum login"});return send(res,200,{user:u})}
if(req.url==="/api/books"&&req.method==="GET")return send(res,200,{books:db.books});
if(req.url==="/api/loans"&&req.method==="GET"){if(!u)return send(res,401,{error:"Belum login"});return send(res,200,{loans:u.role==="pengurus"?db.loans:db.loans.filter(x=>x.email===u.email)})}
if(req.url==="/api/loans"&&req.method==="POST"){if(!u||u.role!=="siswa")return send(res,403,{error:"Akses siswa diperlukan."});let b=await body(req),book=db.books.find(x=>x.id===b.bookId);if(!book||book.stock<1)return send(res,400,{error:"Buku tidak tersedia."});book.stock--;let loan={id:newid("TRX"),bookId:book.id,bookTitle:book.title,name:String(b.name||"").trim(),className:String(b.className||"").trim(),email:u.email,status:"Dipesan",time:new Date().toLocaleString("id-ID")};db.loans.unshift(loan);save();return send(res,201,{loan})}
if(req.url.startsWith("/api/loans/")&&req.method==="PUT"){if(!u||u.role!=="pengurus")return send(res,403,{error:"Akses pengurus diperlukan."});let loan=db.loans.find(x=>x.id===req.url.split("/")[3]);if(!loan)return send(res,404,{error:"Data tidak ditemukan."});let b=await body(req);if(!["Dipesan","Sedang Meminjam","Dikembalikan"].includes(b.status))return send(res,400,{error:"Status tidak valid."});if(loan.status!=="Dikembalikan"&&b.status==="Dikembalikan"){let book=db.books.find(x=>x.id===loan.bookId);if(book)book.stock++}loan.status=b.status;loan.updatedAt=new Date().toLocaleString("id-ID");save();return send(res,200,{loan})}
if(req.url==="/api/books"&&req.method==="POST"){if(!u||u.role!=="pengurus")return send(res,403,{error:"Akses pengurus diperlukan."});let b=await body(req),book={id:newid("BK"),title:String(b.title||"").trim(),author:String(b.author||"Tidak diketahui").trim(),category:String(b.category||"Umum").trim(),stock:Math.max(1,Number(b.stock)||1)};if(!book.title)return send(res,400,{error:"Judul wajib diisi."});db.books.push(book);save();return send(res,201,{book})}
let file=req.url.split("?")[0];if(file==="/")file="/index.html";let full=path.normalize(path.join(PUBLIC,file));if(!full.startsWith(PUBLIC))return send(res,403,{error:"Forbidden"});if(fs.existsSync(full))return send(res,200,fs.readFileSync(full),mime[path.extname(full)]||"application/octet-stream");send(res,404,{error:"Not found"})
}catch(e){console.error(e);send(res,500,{error:"Kesalahan server."})}}).listen(PORT,()=>console.log("Perpus berjalan di http://localhost:"+PORT));
